---
title: "tp2.Rmd"
output: html_document
date: "2023-03-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
data2 = read.csv2("Presidentielle.csv", sep=",", row.names=1)
summary(data2)
```

```{r}
barplot(apply(data2,2,sum)/sum(data2), las=3)
```
```{r}
#verification de la dépendance!
chisq.test(data2)
#c'est ok, les var sont liées
```
```{r}
library(FactoMineR)
res=CA(data2)

```
```{r}
barplot(res$eig[,2])
```
On garde les3 premiers axes

```{r}
plot(res, invisible="row", selectCol = "cos2 0.6")
plot(res, invisible="row", selectCol = "contrib 4")
```
```{r}
summary(res)
```

```{r}
plot(res, axes=c(1,3), invisible="row", selectCol = "contrib 4")
```
Pour éviter que les petits candidat participe a la créations des axes,on met les 2 plus petit candidat en colonne supplémentaire.

```{r}
res1 = CA(data2, row.sup=23, col.sup=c(11, 12))
```

```{r}
plot(res1, invisible = c("row", "row.sup", "col.sup"), selectCol = "contrib 4")
```
```{r}
res$col$contrib
```

```{r}
res$row$contrib
```
```{r}
plot(res1, selectRow="cos2 0.6", selectCol = "cos2 0.6", cex=0.6)#cex=0.6 pour affiché les nom en plus petit, 1 par defaut
```













































































































































