---
title: "tp5.Rmd"
output: html_document
date: "2023-04-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
data = read.table("SAheart.data", sep = ",", header = TRUE, row.names = 1)
data$chd = as.factor(data$chd)
data
```

```{r}
library("rpart")
library("rpart.plot")
arbre = rpart(chd~., data, maxcompete = 4, )
```

```{r}
rpart.plot(arbre, type = 4)#type pour les type d'affichages
print(arbre)
```

```{r}
summary(arbre)
```

```{r}
arbre2=rpart(chd~.,data,control=rpart.control(minsplit=5))
rpart.plot(arbre2, type=2, cex = 0.55)
print(arbre2)
```

On relance l’algorithme avec cp = 0 pour ne pas avoir d’´elagage.

```{r}
arbre=rpart(chd~.,data,control=rpart.control(minsplit=5,cp=0))
rpart.plot(arbre, type=4)
```

```{r}
cp.opt <- arbre$cptable[which.min(arbre$cptable[, "xerror"]), "CP"]
arbre.opt <- prune(arbre,cp=cp.opt)
rpart.plot(arbre.opt, type=4)
```


```{r}
newdata = read.table("SAheart.newdata.data", sep = ",", header = TRUE, row.names = 1)
rpart.predict(arbre.opt, newdata, type = "prob")
rpart.predict(arbre.opt, newdata, type = "class")
```

```{r}
library("randomForest")
forest = randomForest(data)
predict.randomForest(forest, newdata)
```

```{r}
data = read.table("SAheart.data", sep = ",", header = TRUE, row.names = 1)
data$chd = as.numeric(data$chd)  + 2#car le R cpt;
#data$famhist = as.numeric(data$famhist) - 1
library("gbm")
fit.adaboost = gbm(chd ~., data, distribution = "adaboost")

```

```{r}

```





































































































































































































































































































































































